server:
  address: "0.0.0.0:8848"
  prefix: "/api/"

mysql:
  user: "logcms"
  password: "aA123!@#"
  host: "tcp(118.24.10.209:3306)"
  db: "logcms"
  charset: "utf8mb4"
  maxidle: 100
  maxconn: 300

log:
  path: "./log/"
  level: 3
  size: 20 #单位M
